### ISSUE TITLE
logging error

### ISSUE THREAD

**Issue by edit4ever** [astrilchuk/sd2xmltv#21]
I'm getting the following error when trying to run under tvheadend in kodi:

`Traceback (most recent call last):
  File "/storage/.kodi/addons/tools.module.sd2xmltv/sd2xmltv.py", line 376, in <module>
    logging.config.fileConfig(u"logging.cfg", disable_existing_loggers=True)
  File "/usr/lib/python2.7/logging/config.py", line 77, in fileConfig
  File "/usr/lib/python2.7/logging/config.py", line 113, in _create_formatters
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
ConfigParser.NoSectionError: No section: 'formatters'
`

I can run the script under windows - but no log is created.  Also - I noticed that in the develop version - the "util" folder is not included in the addon build.  I can submit a pull request with the change if you want...I'm currently working on incorporating some kodi settings for your options before I submit.

**Comment by edit4ever** [comment]
Looks like a path issue.  When I change line 376 to the hard path:

logging.config.fileConfig(u"/storage/.kodi/addons/tools.module.sd2xmltv/logging.cfg", disable_existing_loggers=True)

The script runs correctly.  Not sure how to fix as I'm not that familiar with Python.
