### ISSUE TITLE
Python AttributeError

### ISSUE THREAD

**Issue by rjbrown99** [astrilchuk/sd2xmltv#23]
I'm seeing a python error as follows:
<pre>
./sd2xmltv.py -u myuser -p mypassword -m
2017-05-20 11:27:56,755 sd2xmltv INFO     Getting SchedulesDirect token.
2017-05-20 11:27:59,437 sd2xmltv INFO     Getting SchedulesDirect status.
2017-05-20 11:28:01,276 sd2xmltv INFO     Account will expire on 2017-12-31 11:59:59 (X days).
2017-05-20 11:28:01,277 sd2xmltv INFO     SchedulesDirect last update at 2017-05-20 15:15:11 (3 hours 12 minutes ago).
2017-05-20 11:28:01,278 sd2xmltv INFO     Message: No known issues.

Manage Account Options:

1. List subscribed lineups
2. Add lineup
3. Remove lineup
4. List lineup channels.

Choose an option or 'x' to exit.
> 2

Add Lineup

Enter 3-character country/region code or 'x' to cancel:
> us
Enter zip/postal code or 'x' to cancel:
> 90210
Traceback (most recent call last):
  File "./sd2xmltv.py", line 376, in <module>
    main()
  File "./sd2xmltv.py", line 370, in main
    app.manage()
  File "./sd2xmltv.py", line 62, in manage
    self._sd.manage()
  File "/home/hts/sd2xmltv/libschedulesdirect/schedulesdirect.py", line 306, in manage
    self._add_lineup()
  File "/home/hts/sd2xmltv/libschedulesdirect/schedulesdirect.py", line 336, in _add_lineup
    headends = self.get_headends_by_postal_code(country_code, postal_code)
  File "/home/hts/sd2xmltv/libschedulesdirect/schedulesdirect.py", line 61, in get_headends_by_postal_code
    return [Headend.from_dict(headend) for headend in headends_dict]
  File "/home/hts/sd2xmltv/libschedulesdirect/common/headend.py", line 30, in from_dict
    headend.headend_id = dct.pop("headend")
AttributeError: 'unicode' object has no attribute 'pop'
</pre>

**Comment by astrilchuk** [comment]
Hi, 

The country/region code requires 3 characters.  In your case you should use 'usa' not 'us'.  I may add country/region validation in the future but it's fairly low priority (lineup management isn't something I would expect to be done very often).

Thanks
